# Site settings
title: Nick Sandu
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nick Sandu
user_description: Nick is a 18-year-old student with a keen interest in computer science. He is also passionate about triathlon and has competed in various races which lead him to qualify for the ITU Multisport World Championships. He has represented Canada and competed in Pontevedra, Spain.
user_title: Student Athlete
email: nsandutri@gmail.com
twitter_username: lorem_ipsum
github_username:  nicksandu
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
